version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_PASSWORD=DygrEtipVq
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=lobby_user
      - MYSQL_DATABASE=lobby_dev
    networks:
      test_network_lobby:
        aliases:
          - database

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      test_network_lobby:
        aliases:
          - redis

  eureka-service:
    image: weplayregistrytest.azurecr.io/eureka-service:1.10.35
    environment:
      - 'SERVICE_PARAMS=--spring.cloud.config.enabled=false --eureka.server.renewalThresholdUpdateIntervalMs=60000 --eureka.server.enableSelfPreservation=false --eureka.server.eviction-interval-timer-in-ms=1000'
      - 'JAVA_OPTS=-Xms256m -Xmx256m'
      - 'XMS_XMX_AUTODETECT=0'
    ports:
      - "8761:8761"
    networks:
      test_network_lobby:
        aliases:
          - eureka-service
    restart: on-failure:2

networks:
  test_network_lobby:
