package tv.weplay.ws.lobby.service.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import lombok.SneakyThrows;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.core.RabbitTemplate;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import tv.weplay.ws.lobby.model.dto.*;
import tv.weplay.ws.lobby.service.EventSenderService;

import java.time.LocalDateTime;

@Slf4j
@Service
@RequiredArgsConstructor
public class RabbitMQEventSenderService implements EventSenderService {

  private static final String EVENT_TYPE = "EVENT_TYPE";
  private static final String DEFAULT_EXCHANGE = "";

  private final RabbitTemplate rabbitTemplate;
  private final ObjectMapper objectMapper;

  @Value("${spring.application.name}")
  private String applicationName;

  @Value("${info.app.version}")
  private String applicationVersion;

  @Value("${info.app.messageProtocolVersion}")
  private String messageProtocolVersion;

  @Override
  @SneakyThrows
  public void prepareAndSendEvent(String data, String queueName) {
    String payload = buildRabbitMQEvent(data);
    log.info("Event to be sent: [{}]", payload);
    rabbitTemplate.convertAndSend(DEFAULT_EXCHANGE, queueName, payload);
    log.info("Message that has been successfully sent: [{}]", payload);
  }

  @Override
  public void prepareAndSendEvent(byte[] data, String queueName) {
    prepareAndSendEvent(new String(data), queueName);
  }

  @SneakyThrows
  //TODO: Rewrite. Just to avoid double quotes generated by jackson when passing json string inside another json string
  private String buildRabbitMQEvent(String body) {
    Event event = new Event(buildEventMetaData(), "%s");
    return String.format(objectMapper.writeValueAsString(event), body);
  }

  private EventMetaData buildEventMetaData() {
    return EventMetaData.builder()
        .type(EVENT_TYPE)
        .sender(new EventSender(applicationName, applicationVersion))
        .eventDateTimes(new EventDateTimes(LocalDateTime.now()))
        .protocol(new EventProtocol(messageProtocolVersion))
        .build();
  }

}
